baseURL = 'http://mielycasarin.com/'
googleAnalytics = ""#googleAnalytics = "UA-123-45"
languageCode = 'pt-br'
title = 'Miely Casarin'
theme = "tema01"
paginate = 4
[params]
    description = "Registre momentos inesquecíveis"
    author = "Miely Casarin"
    authorImage = "/img/01.jpg"

[[menu.main]]
  name = "Sobre"
  url = "/sobre"

[[menu.main]]
  name = "Blog"
  url = "/blog"

[[menu.main]]
  name = "Contato"
  url = "/contato"

[[menu.social]]
    name = "Instagram"
    url = "https://www.instagram.com/miely_fotografia/"
    pre = "<i class='fab fa-instagram'></i>"

[[menu.social]]
    name = "Facebook"
    url = "https://pt-br.facebook.com/mielycasarinfotografias/"
    pre = "<i class='fab fa-facebook'></i>"

[[menu.footer]]
  name = "Sobre"
  url = "/sobre"

[[menu.footer]]
  name = "Privacidade"
  url = "/privacidade"

[[menu.main]]
    name = "Categorias"
    url = "/categories"

#conteudo relacionado
[related]
    threshold = 0 
    includeNewer = true
    toLower = false

    [[related.indices]]
        name = "categories"
        weight = 100

    [[related.indices]]
        name = "date"
        weight = 10

#habilida o uso de html com md
[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
