backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Data', name: 'date', widget: 'datetime' }
      - { label: 'Resumo', name: 'description', widget: 'string' }

      - name: categories
        label : Categorias
        widget: object
        fields:
          - {name: categories, widget: select, options: [Newborn, Acompanhamento, Aniversário], required: true}

      - name: images
        label : Imagems
        widget: object
        fields:
          - { name: image, widget: image }

      - name: slider_section
        label: Slider
        widget: object
        fields:
          - name: images  
            widget: list
            field: {label: Image, name: image, widget: image}
          - {name: background-color, widget: select, options: [Dark, Medium, Light], required: false}

      - { label: 'Conteudo', name: 'body', widget: 'markdown' }