backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
  site_domain: localhost
  repo: cleytonferrari/mielycasarin.com
locale: 'pt'
media_folder: static/img
public_folder: /img
#logo_url: https://your-site.com/images/logo.svg

#editoria, cria um fluxo de trabalho (editar, revisar, pronto, publicar) 
#https://www.netlifycms.org/docs/configuration-options/#publish-mode
#publish_mode: editorial_workflow 

collections:
  - name: pages
    label: 'Páginas'
    files:
      - name: about
        label: 'Sobre'
        file: content/sobre.md
        fields:
          - {label: 'Título', name: title, widget: string}
          - {label: 'Layout', name: layout, widget: string, default: sobre}
          - {label: 'Texto', name: herotext, widget: string, default: 'Registrando momentos inesquecíveis'}
          - label: "Imagem"
            name: "heroimage"
            widget: "image"
            choose_url: true
            default: "/img/autor.webp"
            media_library:
              config:
                multiple: true
          - { label: 'Conteúdo', name: body, widget: markdown}

      - name: privacidade
        label: 'Privacidade'
        file: content/privacidade.md
        fields:
          - {label: 'Título', name: title, widget: string}
          - { label: 'Conteúdo', name: body, widget: markdown}


  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    create: true
    path: '{{year}}/{{slug}}' #Beta https://www.netlifycms.org/docs/beta-features/#folder-collections-path
    media_folder: '/static/img/blog/{{year}}/{{month}}' #Beta https://www.netlifycms.org/docs/beta-features/#folder-collections-media-and-public-folder
    public_folder: '/img/blog/{{year}}/{{month}}' #Beta https://www.netlifycms.org/docs/beta-features/#folder-collections-media-and-public-folder
    #slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    view_filters:
      - label: "Newborn"
        field: categories
        pattern: 'Newborn'
      - label: 'Acompanhamento'
        field: categories
        pattern: 'Acompanhamento'
      - label: Aniversário
        field: categories
        pattern: 'Aniversário'
    view_groups:
      - label: Ano
        field: date
        # groups items based on the value matched by the pattern
        pattern: \d{4}
      - label: Categoria
        field: categories
        # groups items based on the value matched by the pattern
        pattern: '.{20,}'
    editor:
      preview: true
    fields:
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Data', name: 'date', widget: 'datetime', date_format: "DD.MM.YYYY",  time_format: "HH:mm"}
      - { label: 'Resumo', name: 'description', widget: 'string' }

      - name: categories
        label: 'Categorias'
        widget: select
        default: ['Acompanhamento']
        multiple: true
        min: 1
        max: 2
        options:
          - { label: 'Newborn', value: "Newborn" }
          - { label: 'Acompanhamento', value: "Acompanhamento" }
          - { label: 'Aniversário', value: "Aniversário" }

      - name: images
        label: 'Imagens'
        widget: list
        summary: '{{fields.image}}'
        field: {label: Image, name: image, widget: image}

      - { label: 'Conteúdo', name: body, widget: markdown}