backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Data', name: 'date', widget: 'datetime', date_format: "DD.MM.YYYY",  time_format: "HH:mm"}
      - { label: 'Resumo', name: 'description', widget: 'string' }

      - name: categories
        label: 'Categorias'
        widget: select
        default: ['Acompanhamento']
        multiple: true
        min: 1
        max: 2
        options:
          - { label: 'Newborn', value: "Newborn" }
          - { label: 'Acompanhamento', value: "Acompanhamento" }
          - { label: 'Aniversário', value: "Aniversário" }

      - name: images
        label: 'Imagens'
        widget: list
        summary: '{{fields.image}}'
        field: {label: Image, name: image, widget: image}

      - { label: 'Conteúdo', name: body, widget: markdown, sanitize_preview: true}